### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by 5hubham5ingh** [ctn-malone/qjs-ext-lib#7]
Hello, first of all, thanks for these extensions. I've used them in two of my personal projects, [WallRizz](https://github.com/5hubham5ingh/WallRizz) & [Jiffy](https://github.com/5hubham5ingh/Jiffy).
Up until now, I've been debugging using the age-old print("here"), but it's no longer sufficient since the project has grown larger and more complex. So I was wondering what debugging methods you are using, and if there is any debugger for QuickJS that you recommend?

**Comment by ctn-malone** [comment]
Hi. Unfortunately, I'm not aware of any existing debugger for QuickJS except what is mentioned in https://github.com/quickjs-ng/quickjs/issues/119. I usually use the extension to build small/medium script and rely on unit/integration tests to ensure proper behaviour. What kind of issues do you spend the most time investigating/troubleshooting ?

**Comment by 5hubham5ingh** [comment]
> What kind of issues do you spend the most time investigating/troubleshooting ?

In large projects, the stack trace does not work at all. All I get is just the error type and message.
I don't know if it's because I'm using classes instead of just functions because the stack trace is there with errors in scripts with only functions.

Because of this, I had to implement a custom stack trace which works but has made the code a bit messy with unnecessary function calls. [See](https://github.com/5hubham5ingh/WallRizz/blob/main/src/main.js#L40)

The catchError and catchAsyncError are in every method of each class just to catch the error and update the call stack.

This is why I think there must be some better way to do this.

**Comment by ctn-malone** [comment]
> I don't know if it's because I'm using classes instead of just functions because the stack trace is there with errors in scripts with only functions.

Don't you get a stacktrace when running the interpreter with `--unhandled-rejection` ?

**Comment by ctn-malone** [comment]
Why not replace [await wallRizz.run();](https://github.com/5hubham5ingh/WallRizz/blob/main/src/main.js#L312) with one of the following ?

```js
try {
  await wallRizz.run();
}
catch (e) {
  std.err.puts(`${e.constructor.name}: ${e.message}\n${e.stack}`);
  std.exit(1);
}
```

or

```js
wallRizz.run().catch((e) => {
  std.err.puts(`${e.constructor.name}: ${e.message}\n${e.stack}`);
  std.exit(1);
});
```

**Comment by 5hubham5ingh** [comment]
Thanks! I am getting the stack trace in error now.
